################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.c \
../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.c 

OBJS += \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.o \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.o 

C_DEPS += \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.d \
./UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.d 


# Each subdirectory must supply rules for building sources it contributes
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_arc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_blend.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_img.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_label.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_line.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_mask.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_rect.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_draw_triangle.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_buf.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_cache.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.o: ../UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DSTM32F765xx -DUSE_HAL_DRIVER -DDEBUG -c -I../Core/Inc -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Driver" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/GuiPort" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lvgl" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/LIb/Gui/lv_examples" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/Thread" -I"/home/ou/workspace/stm32_ws/BusAdator_Hw/UserFile/UserCode" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"UserFile/LIb/Gui/lvgl/src/lv_draw/lv_img_decoder.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

